name: Pull Request

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-timeout=30s
          --health-start-period=5s
          --health-retries=3
      docker:
        image: docker:20.10.7
        options: --privileged
        env:
          DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t dockerhub-username/pm-api:latest .

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U testuser; do
            echo "Waiting for postgres to be ready..."
            sleep 2
          done

      - name: Run Tests
        run: |
          docker run --rm -d --name pm-api dockerhub-username/pm-api:latest
          docker exec pm-api npm run migrate:deploy
          docker exec pm-api npm run test
          docker stop pm-api