name: Pull Request

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5444:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-timeout=30s
          --health-start-period=5s
          --health-retries=3
      docker:
        image: docker:20.10.7
        options: --privileged
        env:
          DOCKER_BUILDKIT: 1
          DISABLE_PRISMA_SOURCE_MAPS: true
    steps:
      - name: Setup Environment
        run: echo "DATABASE_URL=postgresql://testuser:testpassword@localhost:5444/testdb?schema=public" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5444 -U testuser; do
            echo "Waiting for postgres to be ready..."
            sleep 2
          done

      - name: Prisma Setup
        run: |
          npm run migrate:reset
          npm run prisma:generate 

      - name: Run Tests
        run: |
          ls -l node_modules/@prisma/client/runtime
          npm run test