name: Pull Request

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        env:
          DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t dockerhub-username/pm-api:latest .

      - name: Run Tests
        run: |
          echo "Starting a new container..."
          docker network create pm-network || echo "Network already exists"
          docker run --rm -d --name pm-api dockerhub-username/pm-api:latest --network pm-network
          echo "Running tests..."
          docker exec pm-api npm test
          docker stop pm-api